version: '3'
services:
  db:
    environment:
      POSTGRES_PASSWORD: t4sk
      POSTGRES_USER: task
      POSTGRES_DB: tasks_dbt
  web:
    image: damianofds/web:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
  scheduler:
    image: damianofds/scheduler:latest
    depends_on:
      - db
